# Generated by Django 5.1.6 on 2025-02-08 17:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treballador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('vat', models.CharField(max_length=20)),
                ('codi_entrada', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message="El codi d'entrada ha de ser exactament 4 dígits.", regex='^\\d{4}$'), django.core.validators.MinLengthValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Marcatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipus', models.CharField(choices=[('entrada', 'Entrada'), ('sortida', 'Sortida')], max_length=10)),
                ('treballador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marcatge.treballador')),
            ],
        ),
    ]
