# Generated by Django 5.1.6 on 2025-02-09 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0002_diatreball'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcatge',
            name='dia_treball',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marcatge.diatreball'),
            preserve_default=False,
        ),
    ]
