# Generated by Django 2.2.3 on 2019-07-09 23:09

import django.core.validators
from django.db import migrations, models
import marcatge.validators


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0002_marcatge_treballador'),
    ]

    operations = [
        migrations.AddField(
            model_name='treballador',
            name='codi_entrada',
            field=models.CharField(default=1234, max_length=4, validators=[marcatge.validators.validate_numeric_char, django.core.validators.MinLengthValidator(4)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marcatge',
            name='sortida',
            field=models.DateTimeField(blank=True),
        ),
    ]
