# Generated by Django 5.1.6 on 2025-02-09 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0003_marcatge_dia_treball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcatge',
            name='dia_treball',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marcatge.diatreball'),
        ),
    ]
