# Generated by Django 5.1.6 on 2025-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0005_treballador_jornada_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatreball',
            name='hores_restants',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
