# Generated by Django 5.1.6 on 2025-02-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0008_diatreball_hores_ajustades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treballador',
            name='ajustar_jornada_diaria',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='diatreball',
            name='hores_ajustades',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
