# Generated by Django 5.1.6 on 2025-02-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0009_treballador_ajustar_jornada_diaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diatreball',
            name='marcatges_relacionats_txt_backup',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
