# Generated by Django 5.2.4 on 2025-07-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0013_alter_diatreball_forcar_jornada_diaria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diatreball',
            options={'verbose_name': 'Dia', 'verbose_name_plural': 'Dies'},
        ),
    ]
