# Generated by Django 5.2.4 on 2025-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0014_alter_diatreball_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatreball',
            name='forcar_jornada_diaria',
            field=models.BooleanField(default=False, help_text="Marcar si la jornada laboral d'aquest dia és diferent a la jornada laboral configurada en el treballador.", verbose_name='Jornada laboral diferent de la del treballador?'),
        ),
        migrations.AlterField(
            model_name='diatreball',
            name='hores_ajustades',
            field=models.BooleanField(blank=True, default=False, help_text="Indica si el procés automàtic que corregeix els marcatges ja ha ajustat els marcatges d'aquest dia per fer-los coincidir amb la jornada laboral. Si ja s'ha marcat, no es tornaran a ajustar automàticament. Si es desmarca, a la nit s'ajustaran els marcatges per fer-los coincidir amb la jornada laboral configurada.", verbose_name='Hores ja ajustades a la jornada'),
        ),
        migrations.AlterField(
            model_name='diatreball',
            name='hores_restants',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculat automàticament a través dels marcatges.', max_digits=5, verbose_name='Hores Restants'),
        ),
        migrations.AlterField(
            model_name='diatreball',
            name='hores_totals',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculat automàticament a través dels marcatges.', max_digits=5, verbose_name='Hores Treballades'),
        ),
        migrations.AlterField(
            model_name='diatreball',
            name='nova_jornada_diaria',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Emplenar si la jornada laboral d'aquest dia és diferent a la jornada laboral configurada en el treballador.", max_digits=5, verbose_name='Jornada Laboral Asignada'),
        ),
    ]
