# Generated by Django 2.2.3 on 2019-07-09 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcatge',
            name='treballador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='marcatge.Treballador'),
            preserve_default=False,
        ),
    ]
