# Generated by Django 2.2.3 on 2019-07-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0004_auto_20190711_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcatge',
            name='entrada_ip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='marcatge',
            name='sortida_ip',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
