# Generated by Django 2.2.6 on 2019-12-15 10:35

from django.db import migrations, models
from datetime import timedelta, datetime, time
from django.utils import timezone


def get_time_spent(obj):
    if not obj.entrada:
        return timedelta(seconds=0)
    sortida = obj.sortida
    if not sortida:
        sortida = timezone.now()
    return sortida - obj.entrada


def get_subtotal(obj):
    spent = get_time_spent(obj)
    return spent - timedelta(seconds=spent.seconds, microseconds=spent.microseconds)


def get_subtotal_dia(Marcatge, obj):
    trobats = Marcatge.objects.filter(
        entrada__range=(datetime.combine(obj.entrada, time.min), datetime.combine(obj.entrada, time.max)),
        sortida__isnull=False,
        treballador=obj.treballador
    )
    spent = timedelta(seconds=0)
    for trobat in trobats:
        spent += get_time_spent(trobat)
    return spent - timedelta(seconds=spent.seconds, microseconds=spent.microseconds)


def set_my_defaults(apps, schema_editor):
    Marcatge = apps.get_model('marcatge', 'Marcatge')
    for marcatge in Marcatge.objects.all().iterator():
        marcatge.subtotal = get_subtotal(marcatge)
        marcatge.save()
        marcatge.subtotal_dia = get_subtotal_dia(Marcatge, marcatge)
        marcatge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marcatge', '0005_auto_20190711_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcatge',
            name='subtotal',
            field=models.DurationField(null=True)
        ),
        migrations.AddField(
            model_name='marcatge',
            name='subtotal_dia',
            field=models.DurationField(null=True)
        ),
        migrations.RunPython(set_my_defaults)
    ]
